const casinoLicenses = [
  {
    id: 1,
    name: "Malta Gaming Authority",
    validCountries: [
      "MT",
      "CA",
      "FI",
      "NO",
      "JP",
      "IN",
      "NZ",
      "BR",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "CH",
      "IE",
      "AU",
      "ZA",
    ],
  },
  {
    id: 2,
    name: "Curaçao eGaming",
    validCountries: [
      "CW",
      "CA",
      "FI",
      "NO",
      "JP",
      "IN",
      "NZ",
      "BR",
      "MX",
      "BE",
      "BG",
      "HR",
      "CY",
      "CZ",
      "DK",
      "EE",
      "GR",
      "HU",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "PL",
      "PT",
      "RO",
      "SK",
      "SI",
      "SE",
    ],
  },
  {
    id: 3,
    name: "Gibraltar Gambling Commissioner",
    validCountries: [
      "GI",
      "CA",
      "FI",
      "NO",
      "JP",
      "IN",
      "NZ",
      "BR",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "CH",
      "IE",
      "AU",
      "ZA",
    ],
  },
  {
    id: 4,
    name: "Kahnawake Gaming Commission",
    validCountries: [
      "CA",
      "MX",
      "BR",
      "JP",
      "IN",
      "NZ",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "CH",
      "IE",
      "AU",
      "ZA",
    ],
  },
  {
    id: 5,
    name: "Isle of Man Gambling Supervision Commission",
    validCountries: [
      "IM",
      "CA",
      "FI",
      "NO",
      "JP",
      "IN",
      "NZ",
      "BR",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "CH",
      "IE",
      "AU",
      "ZA",
    ],
  },
  {
    id: 6,
    name: "Alderney Gambling Control Commission",
    validCountries: [
      "GG",
      "CA",
      "FI",
      "NO",
      "JP",
      "IN",
      "NZ",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "CH",
      "IE",
      "AU",
      "ZA",
    ],
  },
  {
    id: 7,
    name: "Antigua and Barbuda Financial Services Regulatory Commission – Division of Gaming",
    validCountries: [
      "AG",
      "CA",
      "MX",
      "BR",
      "JP",
      "IN",
      "NZ",
      "DE",
      "FR",
      "ES",
      "IT",
      "NL",
      "BE",
      "AT",
      "CH",
      "IE",
      "AU",
      "ZA",
    ],
  },
  { id: 8, name: "UK Gambling Commission", validCountries: ["GB"] },
  {
    id: 9,
    name: "New Jersey Division of Gaming Enforcement",
    validCountries: ["US"],
  },
  { id: 10, name: "Pennsylvania Gaming Control Board", validCountries: ["US"] },
  { id: 11, name: "Michigan Gaming Control Board", validCountries: ["US"] },
  { id: 12, name: "Delaware Lottery", validCountries: ["US"] },
  { id: 13, name: "West Virginia Lottery Commission", validCountries: ["US"] },
  {
    id: 14,
    name: "Connecticut Department of Consumer Protection",
    validCountries: ["US"],
  },
  {
    id: 15,
    name: "Alcohol and Gaming Commission of Ontario",
    validCountries: ["CA"],
  },
  { id: 16, name: "Swedish Gambling Authority", validCountries: ["SE"] },
  { id: 17, name: "Danish Gambling Authority", validCountries: ["DK"] },
  {
    id: 18,
    name: "Italian Customs and Monopolies Agency",
    validCountries: ["IT"],
  },
  {
    id: 19,
    name: "Directorate General for the Regulation of Gambling",
    validCountries: ["ES"],
  },
  { id: 20, name: "National Gambling Authority", validCountries: ["FR"] },
  { id: 21, name: "Netherlands Gambling Authority", validCountries: ["NL"] },
  { id: 22, name: "Belgian Gaming Commission", validCountries: ["BE"] },
  {
    id: 23,
    name: "Joint Gambling Authority of the Federal States",
    validCountries: ["DE"],
  },
  { id: 24, name: "Hellenic Gaming Commission", validCountries: ["GR"] },
  {
    id: 25,
    name: "Gaming Regulation and Inspection Service",
    validCountries: ["PT"],
  },
  { id: 26, name: "National Gambling Office", validCountries: ["RO"] },
  { id: 27, name: "Coljuegos", validCountries: ["CO"] },
  {
    id: 28,
    name: "Philippine Amusement and Gaming Corporation",
    validCountries: ["PH"],
  },
  {
    id: 29,
    name: "Betting Control and Licensing Board",
    validCountries: ["KE"],
  },
  {
    id: 30,
    name: "National Lottery Regulatory Commission",
    validCountries: ["NG"],
  },
  {
    id: 31,
    name: "Estonian Tax and Customs Board",
    validCountries: [
      "EE",
      "AT",
      "BE",
      "BG",
      "HR",
      "CY",
      "CZ",
      "DK",
      "FI",
      "FR",
      "DE",
      "GR",
      "HU",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "NL",
      "PL",
      "PT",
      "RO",
      "SK",
      "SI",
      "ES",
      "SE",
    ],
  },
  {
    id: 32,
    name: "Lotteries and Gambling Supervisory Inspection of Latvia",
    validCountries: ["LV"],
  },
  {
    id: 33,
    name: "Gambling Supervisory Authority of Lithuania",
    validCountries: ["LT"],
  },
  {
    id: 34,
    name: "Czech Ministry of Finance – Gambling and Lottery Department",
    validCountries: ["CZ"],
  },
  { id: 35, name: "Slovak Gambling Regulatory Office", validCountries: ["SK"] },
  { id: 36, name: "Swiss Federal Gaming Board", validCountries: ["CH"] },
  {
    id: 37,
    name: "Ukrainian Commission for Regulation of Gambling and Lotteries",
    validCountries: ["UA"],
  },
  {
    id: 38,
    name: "Belarus Ministry of Taxes and Levies",
    validCountries: ["BY"],
  },
  {
    id: 39,
    name: "Georgian Revenue Service – Gambling Division",
    validCountries: ["GE"],
  },
  {
    id: 40,
    name: "Ministry of Finance of Armenia – Gambling Licensing Department",
    validCountries: ["AM"],
  },
  {
    id: 41,
    name: "Serbian Games of Chance Administration",
    validCountries: ["RS"],
  },
  {
    id: 42,
    name: "Montenegrin Games of Chance Administration",
    validCountries: ["ME"],
  },
  {
    id: 43,
    name: "Hungarian Supervisory Authority for Regulatory Affairs",
    validCountries: ["HU"],
  },
  { id: 44, name: "Gaming Board of Tanzania", validCountries: ["TZ"] },
  { id: 45, name: "Gaming Commission of Ghana", validCountries: ["GH"] },
  { id: 46, name: "Barbados Gaming Authority", validCountries: ["BB"] },
  {
    id: 47,
    name: "Jamaica Betting, Gaming & Lotteries Commission",
    validCountries: ["JM"],
  },
  {
    id: 48,
    name: "Sierra Leone Gaming, Lottery and Sports Betting Control Board",
    validCountries: ["SL"],
  },
  { id: 49, name: "Panama Gaming Control Board", validCountries: ["PA"] },
  {
    id: 50,
    name: "Ministry of Foreign Trade and Tourism of Peru",
    validCountries: ["PE"],
  },
  {
    id: 51,
    name: "Lotería de la Ciudad de Buenos Aires (LOTBA)",
    validCountries: ["AR"],
  },
  {
    id: 52,
    name: "Buenos Aires Provincial Institute of Lottery and Casinos (IPLyC)",
    validCountries: ["AR"],
  },
  {
    id: 53,
    name: "Costa Rica Ministry of Finance – Data Processing License (unregulated)",
    validCountries: [],
  },
  {
    id: 54,
    name: "Anjouan Gaming Board",
    validCountries: [
      "IN",
      "BR",
      "MX",
      "ZA",
      "FI",
      "NO",
      "NZ",
      "JP",
      "BE",
      "BG",
      "HR",
      "CY",
      "CZ",
      "DK",
      "EE",
      "GR",
      "HU",
      "IE",
      "IT",
      "LV",
      "LT",
      "LU",
      "MT",
      "PL",
      "PT",
      "RO",
      "SK",
      "SI",
      "SE",
    ],
  },
  {
    id: 55,
    name: "Tobique Gaming Commission",
    validCountries: ["CA", "FI", "NO", "JP", "IN", "NZ", "BR", "MX"],
  },
];

const casinoData = [
  {
    casino_name: "Videoslots",
    bonus: "100% up to €200 + 11 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "no wagering requirement",
    free_spin_value: "€0.10/spin",
    info: "This is a 'wager first' bonus, where the bonus is paid out in 10% increments as the deposit is wagered",
    licenses: [1, 8, 16, 17, 15], // Malta Gaming Authority, UK Gambling Commission, Swedish Gambling Authority, Spillemyndigheden (Danish Gambling Authority), Alcohol and Gaming Commission of Ontario
    updated: "2025-03-27",
  },
  {
    casino_name: "Boost Casino",
    bonus: "100% 250 € asti + 50 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "30x",
    free_spin_value: "€0.10/spin",
    info: "Deposited funds are used first. The bonus is 'non-sticky'.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-27",
  },
  {
    casino_name: "Pommi Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Pommi Casino offers no sign-up bonus.",
    licenses: [2], // Curacao Gaming Control Board (mapped to Curaçao eGaming as closest match)
    updated: "2025-03-27",
  },
  {
    casino_name: "Paratiisi Casino",
    bonus: "300 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "€0.10/spin",
    info: "100 free spins per day are handed out over 3 days.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-27",
  },
  {
    casino_name: "Bethard",
    bonus: "100% up to €50 + 20 free spins",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "10x",
    free_spin_value: "€0.20/spin",
    info: "",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-28",
  },
  {
    casino_name: "Shokki Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Pommi Casino offers no sign-up bonus.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-28",
  },
  {
    casino_name: "Lucky Trunk Casino",
    bonus: "100% up to €250 + 50 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "Pommi Casino offers no sign-up bonus.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-28",
  },
  {
    casino_name: "Hillo Casino",
    bonus: "100 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "50x",
    free_spin_value: "€0.20/spin",
    info: "50 free spins per day are handed out over 2 days.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-28",
  },
  {
    casino_name: "Teho Casino",
    bonus: "150% up to €600",
    wagering_requirement_bonus: "80x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "The bonus is 'sticky'.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-28",
  },
  {
    casino_name: "Dazzlehand Casino",
    bonus: "100% up to €200 + 200 free spins",
    wagering_requirement_bonus: "60x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-28",
  },
  {
    casino_name: "21 Casino",
    bonus: "121% up to €300 + 21 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "The free spins are awarded on registration.",
    licenses: [1, 8], // Malta Gaming Authority, UK Gambling Commission
    updated: "2025-03-28",
  },
  {
    casino_name: "Wild Robin Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 10 days.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-28",
  },
  {
    casino_name: "RX Casino",
    bonus: "150% up to €5000",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "The max win from the bonus is 3x the bonus value.",
    licenses: [2, 54], // Curacao Gaming Control Board, Anjouan Gaming
    updated: "2025-03-28",
  },
  {
    casino_name: "Kaahaus Casino",
    bonus: "100 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-28",
  },
  {
    casino_name: "Betizy Casino",
    bonus: "100% up to €250 + 50 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-28",
  },
  {
    casino_name: "Slot it Casino",
    bonus: "100% up to €500",
    wagering_requirement_bonus: "36x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-28",
  },
  {
    casino_name: "Casumo Casino",
    bonus: "100% up to €300 + 20 free spins",
    wagering_requirement_bonus: "60x",
    wagering_requirement_free_spins: "30x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [3], // H.M. Government of Gibraltar (mapped to Gibraltar Gambling Commissioner)
    updated: "2025-03-28",
  },
  {
    casino_name: "Lunubet Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-03-28",
  },
  {
    casino_name: "Epicbet Casino",
    bonus: "Up to €300",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "This is a 'wager first' bonus where €10 is handed out for every €400 wagered up to a max of €300 in total.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-28",
  },
  {
    casino_name: "Saletti Casino",
    bonus: "100% up to €500 + 50 free spins",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-28",
  },
  {
    casino_name: "Possu Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-29",
  },
  {
    casino_name: "Winz.io Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-29",
  },
  {
    casino_name: "Reipas Casino",
    bonus: "100% up to €500 + 50 free spins",
    wagering_requirement_bonus: "80x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.25/spin",
    info: "Max win from free spins €20.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-29",
  },
  {
    casino_name: "Kingpalace Casino",
    bonus: "100% up to €2000 + 200 free spins",
    wagering_requirement_bonus: "60x",
    wagering_requirement_free_spins: "30x",
    free_spin_value: "€0.10/spin",
    info: "The first deposit bonus depends on the deposit amount. A €20 deposit will give 200% bonus up to €50 with a 50x wagering requirement. A €50 deposit will give 150% bonus up to €350 with a 40x wagering requirement. A €500 deposit will give 100% up to €2000 with a 60x wagering requirement.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-29",
  },
  {
    casino_name: "Arctic Casino",
    bonus: "10 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€1/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-29",
  },
  {
    casino_name: "Lucky Nordic Casino",
    bonus: "50 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "€1/spin",
    info: "The spin value of the free spins depend on the first deposit amount. A €20 deposit gives a €0.10 spin value. A €100 deposit gives a €0.50 spin value. A €200 deposit gives a €1 spin value.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-29",
  },
  {
    casino_name: "Fruta Casino",
    bonus: "200 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "€0.20/spin",
    info: "200 free spins per day are handed out over 4 days in different games where the spin value ranges from €0.10 to €0.20.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-29",
  },
  {
    casino_name: "Dynabet Casino",
    bonus: "100% up to €2000",
    wagering_requirement_bonus: "30x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-29",
  },
  {
    casino_name: "Budsino Casino",
    bonus: "100% up to €100",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-30",
  },
  {
    casino_name: "Highroller Casino",
    bonus: "200 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "€0.20/spin",
    info: "200 free spins per day are handed out over 10 days in different games where the spin value ranges from €0.10 to €0.20.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Taika Spins Casino",
    bonus: "100% up to €250 + 50 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-30",
  },
  {
    casino_name: "Casino Vice",
    bonus: "100% up to €500 + 125 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.20/spin",
    info: "125 free spins per day are handed out over 5 days in different games.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Fat Pirate Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "125 free spins per day are handed out over 5 days in different games.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Qbet Casino",
    bonus: "10 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€1/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Trust Dice Win Casino",
    bonus: "200% up to €30000 + 20 free spins",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Casino Joy",
    bonus: "200% up to €1000 + 100 free spins",
    wagering_requirement_bonus: "80x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Wildsino Casino",
    bonus: "100% up to €1000 + 300 free spins",
    wagering_requirement_bonus: "80x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [54], // Anjouan Gaming
    updated: "2025-03-30",
  },
  {
    casino_name: "Be On Bet Casino",
    bonus: "150% up to €450 + 100 free spins",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Be On Bet Casino",
    bonus: "100% up to €250 + 50 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Bet Label Casino",
    bonus: "100% up to €300 + 30 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "PrimeBetz Casino",
    bonus: "100% up to €500 + 100 free spins",
    wagering_requirement_bonus: "50x",
    wagering_requirement_free_spins: "50x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 5 days in different games.",
    licenses: [4], // Kahnawake Gaming Commission
    updated: "2025-03-30",
  },
  {
    casino_name: "Paripesa Casino",
    bonus: "100% up to €300 + 30 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 5 days in different games.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-30",
  },
  {
    casino_name: "Betrix Casino",
    bonus: "100% up to €250 + 50 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 5 days in different games.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-03-30",
  },
  {
    casino_name: "AllySpin Casino",
    bonus: "100% up to €500",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [54], // Anjouan Gaming
    updated: "2025-03-30",
  },
  {
    casino_name: "Spinaro Casino",
    bonus: "100% up to €1000 + 50 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [54], // Anjouan Gaming
    updated: "2025-03-30",
  },
  {
    casino_name: "Impressario Casino",
    bonus: "100% up to €1000 + 100 free spins",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [4], // Kahnawake Gaming Commission
    updated: "2025-03-30",
  },
  {
    casino_name: "Trivelabet Casino",
    bonus: "200% up to €1000",
    wagering_requirement_bonus: "30x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-31",
  },
  {
    casino_name: "Magius Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 10 days in different games.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-31",
  },
  {
    casino_name: "Fun Bet Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 10 days in different games.",
    licenses: [], // "n/a" mapped to empty array
    updated: "2025-03-31",
  },
  {
    casino_name: "Hotbet Casino",
    bonus: "100% up to €200",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [], // "n/a" mapped to empty array
    updated: "2025-03-31",
  },
  {
    casino_name: "Casino Vibes",
    bonus: "100% up to €300 + 50 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-31",
  },
  {
    casino_name: "Gemobet Casino",
    bonus: "100 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "30x",
    free_spin_value: "€0.10/spin",
    info: "20 free spins per day are handed out over 5 days.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-03-31",
  },
  {
    casino_name: "Tuohi Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "0x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "n/a",
    info: "The first deposit awards 1 spin on a prize wheel. No guaranteed wins but a max win of €5000.",
    licenses: [5], // Gambling Supervision Commission Isle of Man
    updated: "2025-03-31",
  },
  {
    casino_name: "Pelikioski Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "The first deposit awards a mystery prize. No guaranteed wins but a max win of €500.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-03-31",
  },
  {
    casino_name: "Zip Casino",
    bonus: "100% up to €1000 + 50 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [54], // Anjouan Gaming
    updated: "2025-03-31",
  },
  {
    casino_name: "NetBet Casino",
    bonus: "100% up to €500 + 500 free spins",
    wagering_requirement_bonus: "30x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.05/spin",
    info: "500 free spins are handed out in varying amounts over 7 days, with 50 on day one.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-01",
  },
  {
    casino_name: "Spin247 Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.05/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-01",
  },
  {
    casino_name: "Huikee Casino",
    bonus: "150% up to €400 + 50 free spins",
    wagering_requirement_bonus: "80x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-01",
  },
  {
    casino_name: "ReSpin Casino",
    bonus: "Up to €300",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "This is a 'wager first' bonus where €10 is handed out for every €400 wagered up to a max of €300 in total.",
    licenses: [31], // Estonian Tax and Customs Board
    updated: "2025-04-02",
  },
  {
    casino_name: "Slotti Casino",
    bonus: "100 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "50x",
    free_spin_value: "€0.20/spin",
    info: "100 free spins are handed out in batches of 50 on the first day, 25 free spins on the second day, and 25 free spins on the third day.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "iBet Casino",
    bonus: "10 free spins",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€1/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-02",
  },
  {
    casino_name: "Pistolo Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-02",
  },
  {
    casino_name: "Legiano Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-02",
  },
  {
    casino_name: "Mr Punter",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-02",
  },
  {
    casino_name: "Lunubet Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-02",
  },
  {
    casino_name: "Lysti Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "No bonus on offer.",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "Spinfest Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [], // "n/a" mapped to empty array
    updated: "2025-04-05",
  },
  {
    casino_name: "Slot it Casino",
    bonus: "100% up to €500",
    wagering_requirement_bonus: "36x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [2], // Curacao Gaming Control Board
    updated: "2025-04-05",
  },
  {
    casino_name: "Roby Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-05",
  },
  {
    casino_name: "BassBet Casino",
    bonus: "100% up to €500 + 200 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "200 free spins are handed out in amounts of 20 spins per day over a span of 10 days.",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-05",
  },
  {
    casino_name: "Mammona Casino",
    bonus: "100% up to €500 + 50 free spins",
    wagering_requirement_bonus: "40x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.20/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-05",
  },
  {
    casino_name: "Wheelz Casino",
    bonus: "100% up to €300 + 100 free spins",
    wagering_requirement_bonus: "35x",
    wagering_requirement_free_spins: "35x",
    free_spin_value: "€0.10/spin",
    info: "Free spins are given out in batches of 10 per day over a span of 10 days.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-05",
  },
  {
    casino_name: "Kruuna Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "No bonus on offer.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-05",
  },
  {
    casino_name: "Ninja Casino",
    bonus: "n/a",
    wagering_requirement_bonus: "n/a",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "No bonus on offer.",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-05",
  },
  {
    casino_name: "Power Up Casino",
    bonus: "100% up to €1000 + 100 free spins",
    wagering_requirement_bonus: "70x",
    wagering_requirement_free_spins: "40x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [54], // Anjouan Gaming
    updated: "2025-04-05",
  },
  {
    casino_name: "N1 Casino",
    bonus: "100% up to €1000 + 150 free spins",
    wagering_requirement_bonus: "50x",
    wagering_requirement_free_spins: "50x",
    free_spin_value: "€0.10/spin",
    info: "n/a",
    licenses: [1], // Malta Gaming Authority
    updated: "2025-04-05",
  },
  {
    casino_name: "Bally Bet Casino, USA",
    bonus: "Up to $100 in bonus back + $50 bonus bet tokens",
    wagering_requirement_bonus: "5x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "One of the following applies: (1) Net Loss exceeds 90% of the first Deposit at any time within seven (7) calendar days after placing the first Deposit and first Wager, the value of their first Deposit, up to a maximum of $100 in Bonus Money is awarded, or (2) if the Net Loss does not exceed 90% of the first Deposit after the conclusion of the seven (7) calendar days after placing the first Deposit and first Wager, the value of the Net Loss, up to a maximum of $100 in Bonus Money is awarded. Bonus bet tokens are non-withdrawable. Only winnings generated from wagers with bonus bet tokens are withdrawable",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "Bet365, USA",
    bonus: "Up to 500 bonus spins",
    wagering_requirement_bonus: "5x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "$0.20",
    info: "Take a spin on the New Player Offer reels for the chance to win five, 10, or 15 bonus spins. You will need to do this 10 out of the next 20 days, and a maximum of 500 spins are up for grabs.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "BetMGM, USA",
    bonus: "$25 registration bonus + 100% up to $1000",
    wagering_requirement_bonus: "15x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "The registration bonus has a 1x wagering requirement.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "BetRivers Casino, USA",
    bonus: "Up to $500 loss rebate",
    wagering_requirement_bonus: "1x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Rebate of up to $500 on any losses you sustain in your first 24 hours. The rebate will be paid in bonus credits, and you just need to satisfy a simple 1x playthrough requirement before they convert to withdrawable cash.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "Borgata Online Casino, USA",
    bonus: "$20 registration bonus + 100% up to $1000",
    wagering_requirement_bonus: "15x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Any winnings you earn from your $20 bonus can't be withdrawn until you (1) make a deposit, and (2) meet a 1x playthrough requirement on the winnings.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "Caesars Palace Online Casino, USA",
    bonus: "100% up to $2500",
    wagering_requirement_bonus: "30x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Wagering requirement applies to both deposit + bonus.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "DraftKings Casino, USA",
    bonus: "$35 bonus + 500 free spins + $1000 bonus",
    wagering_requirement_bonus: "10x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "$0.08/spin",
    info: "1x wagering requirement on the $35 first deposit bonus. Wager $5 and get 500 free spins. Wager another $1000 and get $1000 in bonus with a 10x wagering requirement.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-02",
  },
  {
    casino_name: "Fanatics Casino, USA",
    bonus: "$100 bonus",
    wagering_requirement_bonus: "1x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Wager $10 and get $100 casino bonus with x1 wagering requirement.",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
  {
    casino_name: "FanDuel Casino, USA",
    bonus: "$40 bonus + 350 free spins",
    wagering_requirement_bonus: "1x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "$0.20/spin",
    info: "Free spins are given out in batches of 50 over a span of 7 days.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-04",
  },
  {
    casino_name: "Golden Nugget Casino, USA",
    bonus: "250 free spins + lossback up to $1000",
    wagering_requirement_bonus: "1x",
    wagering_requirement_free_spins: "1x",
    free_spin_value: "$0.08/spin",
    info: "Free spins are given out in batches of 50 over a span of 7 days. Lossback up to $1000 for the first 24 hours.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-04",
  },
  {
    casino_name: "Hard Rock Bet, USA",
    bonus: "100% up to $1000 + 500 free spins",
    wagering_requirement_bonus: "20x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "$0.25/spin",
    info: "n/a",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
  {
    casino_name: "Horseshoe Casino, USA",
    bonus: "100% up to $1250",
    wagering_requirement_bonus: "15x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
  {
    casino_name: "Jackpot City Casino, USA",
    bonus: "100% up to $1000 + 20 free spins",
    wagering_requirement_bonus: "25x",
    wagering_requirement_free_spins: "30x",
    free_spin_value: "$0.10/spin",
    info: "n/a",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
  {
    casino_name: "Monopoly Casino, USA",
    bonus: "Up to $100 loss back",
    wagering_requirement_bonus: "1x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "Refund up to $100 on the first deposit.",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
  {
    casino_name: "PartyCasino, USA",
    bonus: "200% up to $100",
    wagering_requirement_bonus: "10x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "$0.10/spin",
    info: "n/a",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-04",
  },
  {
    casino_name: "PlayStar Casino, USA",
    bonus: "100% up to $500 + 100 free spins",
    wagering_requirement_bonus: "30x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "$0.10/spin",
    info: "n/a",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
  {
    casino_name: "Spin Palace, USA",
    bonus: "50% up to $1000 + 20 free spins",
    wagering_requirement_bonus: "30x",
    wagering_requirement_free_spins: "0x",
    free_spin_value: "$0.10/spin",
    info: "20 free spins on sign-up. Note that both the deposit amount and bonus amount has a 30x wagering requirement, thus resulting in the real wagering requirement being higher than 30x.",
    licenses: [9, 10], // New Jersey Division of Gaming Enforcement, Pennsylvania Gaming Control Board
    updated: "2025-04-04",
  },
  {
    casino_name: "Wheel of Fortune Casino, USA",
    bonus: "100% up to $40",
    wagering_requirement_bonus: "15x",
    wagering_requirement_free_spins: "n/a",
    free_spin_value: "n/a",
    info: "n/a",
    licenses: [9], // New Jersey Division of Gaming Enforcement
    updated: "2025-04-04",
  },
];

export default function handler(req, res) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const location = req.query.location;

  if (!location) {
    return res.status(400).json({ error: "Location parameter is required" });
  }

  // Find matching license in casinoData
  const filteredCasinos = filterCasinosByCountry(location);

  res.status(200).json({
    casinos: filteredCasinos,
  });
}

function filterCasinosByCountry(country) {
  const licenses = casinoLicenses.filter((l) =>
    l.validCountries.includes(country.toUpperCase())
  );
  return casinoData
    .filter((casino) => {
      // filter casino that has at least one license that is valid in the country
      return casino.licenses.some((id) => licenses.some((l) => l.id === id));
    })
    .map((casino) => ({
      ...casino,
      licenses: casino.licenses
        .map((id) => {
          const license = casinoLicenses.find((l) => l.id === id);
          return license ? license.name : null;
        })
        .filter(Boolean), // Remove any null values in case a license ID wasn't found
    }));
}
